"""Grundschema anlegen

Revision ID: d6df0a563ea8
Revises:
Erstellt: 2026-07-28 16:36:27.831451
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "d6df0a563ea8"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=True),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_audit_events_event_type"), ["event_type"], unique=False
        )

    op.create_table(
        "settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value_json", sa.Text(), nullable=False),
        sa.Column("is_secret", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_settings")),
    )
    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_settings_key"), ["key"], unique=True)

    op.create_table(
        "templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.Column("html_content", sa.Text(), nullable=False),
        sa.Column("css_content", sa.Text(), nullable=False),
        sa.Column("width_mm", sa.Float(), nullable=False),
        sa.Column("height_mm", sa.Float(), nullable=False),
        sa.Column("dpi", sa.Integer(), nullable=False),
        sa.Column("output_format", sa.String(length=8), nullable=False),
        sa.Column("qr_content_mode", sa.String(length=16), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("is_builtin", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("dpi >= 50 AND dpi <= 1200", name=op.f("ck_templates_dpi_plausible")),
        sa.CheckConstraint("height_mm > 0", name=op.f("ck_templates_height_positive")),
        sa.CheckConstraint("width_mm > 0", name=op.f("ck_templates_width_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_templates")),
        sa.UniqueConstraint("name", name=op.f("uq_templates_name")),
    )
    op.create_table(
        "workflow_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("requested_spool_count", sa.Integer(), nullable=False),
        sa.Column("created_spool_ids_json", sa.Text(), nullable=False),
        sa.Column("print_job_ids_json", sa.Text(), nullable=False),
        sa.Column("request_payload_json", sa.Text(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "requested_spool_count >= 1", name=op.f("ck_workflow_runs_spool_count_positive")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_runs")),
    )
    with op.batch_alter_table("workflow_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_workflow_runs_idempotency_key"), ["idempotency_key"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_workflow_runs_status"), ["status"], unique=False)

    op.create_table(
        "printers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("queue_name", sa.String(length=128), nullable=False),
        sa.Column("backend_type", sa.String(length=16), nullable=False),
        sa.Column("cups_server", sa.String(length=255), nullable=True),
        sa.Column("cups_port", sa.Integer(), nullable=True),
        sa.Column("use_tls", sa.Boolean(), nullable=False),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("model", sa.String(length=255), nullable=True),
        sa.Column("capabilities_json", sa.Text(), nullable=True),
        sa.Column("default_template_id", sa.Integer(), nullable=True),
        sa.Column("label_width_mm", sa.Float(), nullable=False),
        sa.Column("label_height_mm", sa.Float(), nullable=False),
        sa.Column("dpi", sa.Integer(), nullable=False),
        sa.Column("horizontal_offset_mm", sa.Float(), nullable=False),
        sa.Column("vertical_offset_mm", sa.Float(), nullable=False),
        sa.Column("scale_percent", sa.Float(), nullable=False),
        sa.Column("copies", sa.Integer(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_status", sa.String(length=64), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("copies >= 1", name=op.f("ck_printers_copies_positive")),
        sa.CheckConstraint("label_height_mm > 0", name=op.f("ck_printers_label_height_positive")),
        sa.CheckConstraint("label_width_mm > 0", name=op.f("ck_printers_label_width_positive")),
        sa.CheckConstraint("scale_percent > 0", name=op.f("ck_printers_scale_positive")),
        sa.ForeignKeyConstraint(
            ["default_template_id"],
            ["templates.id"],
            name=op.f("fk_printers_default_template_id_templates"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_printers")),
        sa.UniqueConstraint("queue_name", name=op.f("uq_printers_queue_name")),
    )
    op.create_table(
        "print_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("spoolman_spool_id", sa.Integer(), nullable=False),
        sa.Column("printer_id", sa.Integer(), nullable=True),
        sa.Column("template_id", sa.Integer(), nullable=True),
        sa.Column("workflow_run_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("copies", sa.Integer(), nullable=False),
        sa.Column("rendered_file_path", sa.String(length=512), nullable=True),
        sa.Column("payload_hash", sa.String(length=64), nullable=True),
        sa.Column("cups_job_id", sa.Integer(), nullable=True),
        sa.Column("cups_job_state", sa.String(length=32), nullable=True),
        sa.Column("cups_job_state_reasons", sa.String(length=512), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("copies >= 1", name=op.f("ck_print_jobs_copies_positive")),
        sa.ForeignKeyConstraint(
            ["printer_id"],
            ["printers.id"],
            name=op.f("fk_print_jobs_printer_id_printers"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["templates.id"],
            name=op.f("fk_print_jobs_template_id_templates"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_run_id"],
            ["workflow_runs.id"],
            name=op.f("fk_print_jobs_workflow_run_id_workflow_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_print_jobs")),
    )
    with op.batch_alter_table("print_jobs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_print_jobs_payload_hash"), ["payload_hash"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_print_jobs_printer_id"), ["printer_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_print_jobs_spoolman_spool_id"), ["spoolman_spool_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_print_jobs_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_print_jobs_workflow_run_id"), ["workflow_run_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("print_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_print_jobs_workflow_run_id"))
        batch_op.drop_index(batch_op.f("ix_print_jobs_status"))
        batch_op.drop_index(batch_op.f("ix_print_jobs_spoolman_spool_id"))
        batch_op.drop_index(batch_op.f("ix_print_jobs_printer_id"))
        batch_op.drop_index(batch_op.f("ix_print_jobs_payload_hash"))

    op.drop_table("print_jobs")
    op.drop_table("printers")
    with op.batch_alter_table("workflow_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workflow_runs_status"))
        batch_op.drop_index(batch_op.f("ix_workflow_runs_idempotency_key"))

    op.drop_table("workflow_runs")
    op.drop_table("templates")
    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_settings_key"))

    op.drop_table("settings")
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_events_event_type"))

    op.drop_table("audit_events")
    # ### end Alembic commands ###
